const fs = require('fs');
const path = require('path');
const SCRIPTS_DIR = path.join(process.env.USERPROFILE, 'AppData', 'Roaming', 'cultivation', 'grasscutter', 'scripts');

const quests = {
  'main/quest_30003.lua': [
    '-- 主线：巨龙与自由之歌',
    'function OnQuestStart(player)',
    '  player:SendMessage("风魔龙已被击败，但蒙德的危机尚未解除...")',
    '  player:AddQuestStep("前往骑士团总部")',
    '  player:AddQuestStep("与琴团长会面")',
    '  player:AddQuestStep("参加授勋仪式")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 1 then player:SendMessage("骑士团总部就在前方")',
    '  elseif stepId == 2 then player:GiveItem(201, 150)',
    '  elseif stepId == 3 then player:GiveItem(223, 20000); player:GiveItem(10000015, 1); player:CompleteQuest(30003) end',
    'end',
  ].join('\n'),
  'main/quest_30004.lua': [
    '-- 主线：璃月七星',
    'function OnQuestStart(player)',
    '  player:SendMessage("你抵达了璃月港，这里正在筹备请仙典仪...")',
    '  player:AddQuestStep("前往璃月港")',
    '  player:AddQuestStep("参加请仙典仪")',
    '  player:AddQuestStep("调查事件真相")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 3 then player:GiveItem(201, 200); player:CompleteQuest(30004) end',
    'end',
  ].join('\n'),
  'world/quest_40002.lua': [
    '-- 世界任务：轻策庄的秘宝',
    'function OnQuestStart(player)',
    '  player:SendMessage("轻策庄的老人告诉你，山上藏着祖先留下的宝物...")',
    '  player:AddQuestStep("寻找第一块石碑")',
    '  player:AddQuestStep("寻找第二块石碑")',
    '  player:AddQuestStep("解开机关，打开宝库")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 3 then player:GiveItem(201, 80); player:GiveItem(223, 5000); player:GiveItem(104, 3); player:CompleteQuest(40002) end',
    'end',
  ].join('\n'),
  'world/quest_40003.lua': [
    '-- 世界任务：孤云阁的试炼',
    'function OnQuestStart(player)',
    '  player:SendMessage("孤云阁上有一座古老的试炼场...")',
    '  player:AddQuestStep("击败第一波敌人")',
    '  player:AddQuestStep("击败第二波敌人")',
    '  player:AddQuestStep("击败试炼守卫")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 3 then player:GiveItem(201, 100); player:GiveItem(215, 10); player:CompleteQuest(40003) end',
    'end',
  ].join('\n'),
  'world/quest_40004.lua': [
    '-- 世界任务：望舒客栈的秘密',
    'function OnQuestStart(player)',
    '  player:SendMessage("望舒客栈的老板娘似乎有秘密任务交给你...")',
    '  player:AddQuestStep("与老板娘对话")',
    '  player:AddQuestStep("收集璃月特产")',
    '  player:AddQuestStep("将特产交给老板娘")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 3 then player:GiveItem(201, 60); player:CompleteQuest(40004) end',
    'end',
  ].join('\n'),
  'world/quest_40005.lua': [
    '-- 世界任务：雪山探险',
    'function OnQuestStart(player)',
    '  player:SendMessage("龙脊雪山深处传来奇怪的声响...")',
    '  player:AddQuestStep("前往雪山营地")',
    '  player:AddQuestStep("调查古代遗迹")',
    '  player:AddQuestStep("击败遗迹守卫")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 3 then player:GiveItem(201, 120); player:CompleteQuest(40005) end',
    'end',
  ].join('\n'),
  'story/quest_50002.lua': [
    '-- 传说：迪卢克 - 暗夜英雄',
    'function OnQuestStart(player)',
    '  if not player:HasCharacter(10000006) then player:AddCharacter(10000006); player:SendMessage("获得5星角色：迪卢克！") end',
    '  player:SendMessage("迪卢克邀请你调查蒙德城外的深渊教团活动")',
    '  player:AddQuestStep("前往奔狼领")',
    '  player:AddQuestStep("击败深渊法师")',
    '  player:AddQuestStep("与迪卢克对话")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 3 then player:GiveItem(201, 60); player:CompleteQuest(50002) end',
    'end',
  ].join('\n'),
  'story/quest_50003.lua': [
    '-- 传说：刻晴 - 玉衡星陨',
    'function OnQuestStart(player)',
    '  if not player:HasCharacter(10000008) then player:AddCharacter(10000008); player:SendMessage("获得5星角色：刻晴！") end',
    '  player:AddQuestStep("跟随刻晴巡查璃月港")',
    '  player:AddQuestStep("解决商业纠纷")',
    '  player:AddQuestStep("返回月海亭")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 3 then player:GiveItem(201, 60); player:CompleteQuest(50003) end',
    'end',
  ].join('\n'),
  'story/quest_50004.lua': [
    '-- 传说：钟离 - 尘世闲游',
    'function OnQuestStart(player)',
    '  player:SendMessage("钟离邀请你一起去听戏...")',
    '  player:AddQuestStep("前往和裕茶楼")',
    '  player:AddQuestStep("听钟离讲述璃月历史")',
    '  player:AddQuestStep("参观古老的遗迹")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 3 then player:GiveItem(201, 60); player:CompleteQuest(50004) end',
    'end',
  ].join('\n'),
  'story/quest_50005.lua': [
    '-- 传说：七七 - 不卜庐的采药童',
    'function OnQuestStart(player)',
    '  if not player:HasCharacter(10000003) then player:AddCharacter(10000003); player:SendMessage("获得5星角色：七七！") end',
    '  player:SendMessage("七七需要你的帮助去采药...")',
    '  player:AddQuestStep("采集琉璃袋x5")',
    '  player:AddQuestStep("采集清心x3")',
    '  player:AddQuestStep("回到不卜庐")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 3 then player:GiveItem(201, 60); player:CompleteQuest(50005) end',
    'end',
  ].join('\n'),
  'event/quest_60002.lua': [
    '-- 活动：逐月节美食大赛',
    'function OnQuestStart(player)',
    '  player:SendMessage("逐月节到了！参加美食大赛赢取丰厚奖励")',
    '  player:AddQuestStep("收集食材x10")',
    '  player:AddQuestStep("制作料理x3")',
    '  player:AddQuestStep("提交参赛作品")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 3 then player:GiveItem(201, 200); player:GiveItem(101, 5); player:CompleteQuest(60002) end',
    'end',
  ].join('\n'),
  'event/quest_60003.lua': [
    '-- 活动：风花节飞行挑战',
    'function OnQuestStart(player)',
    '  player:SendMessage("风花节飞行挑战开始！")',
    '  player:AddQuestStep("完成飞行路线1")',
    '  player:AddQuestStep("完成飞行路线2")',
    '  player:AddQuestStep("领取奖励")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 3 then player:GiveItem(201, 150); player:GiveItem(104, 5); player:CompleteQuest(60003) end',
    'end',
  ].join('\n'),
  'event/quest_60004.lua': [
    '-- 活动：海灯节烟花大会',
    'function OnQuestStart(player)',
    '  player:SendMessage("海灯节烟花大会盛大开幕！")',
    '  player:AddQuestStep("观看烟花表演")',
    '  player:AddQuestStep("放飞霄灯")',
    '  player:AddQuestStep("领取海灯节礼物")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 3 then player:GiveItem(201, 300); player:GiveItem(101, 10); player:CompleteQuest(60004) end',
    'end',
  ].join('\n'),
  'event/quest_60005.lua': [
    '-- 活动：佳酿节品酒会',
    'function OnQuestStart(player)',
    '  player:SendMessage("佳酿节到了！天使的馈赠正在举办品酒会")',
    '  player:AddQuestStep("品尝各种美酒")',
    '  player:AddQuestStep("与迪卢克对话")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 2 then player:GiveItem(201, 100); player:CompleteQuest(60005) end',
    'end',
  ].join('\n'),
  'event/quest_60006.lua': [
    '-- 活动：机关奇谭挑战',
    'function OnQuestStart(player)',
    '  player:SendMessage("机关奇谭挑战赛开始！使用机关击败敌人")',
    '  player:AddQuestStep("通过第1关")',
    '  player:AddQuestStep("通过第3关")',
    '  player:AddQuestStep("通过第5关")',
    'end',
    'function OnQuestStepComplete(player, stepId)',
    '  if stepId == 3 then player:GiveItem(201, 200); player:GiveItem(224, 5); player:CompleteQuest(60006) end',
    'end',
  ].join('\n'),
};

let created = 0;
for (const [relPath, content] of Object.entries(quests)) {
  const fullPath = path.join(SCRIPTS_DIR, relPath);
  const dir = path.dirname(fullPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  if (!fs.existsSync(fullPath)) {
    fs.writeFileSync(fullPath, content, 'utf-8');
    created++;
  }
}
console.log('Created', created, 'new quest scripts');
['main','world','story','event'].forEach(d => {
  const dir = path.join(SCRIPTS_DIR, d);
  if (fs.existsSync(dir)) console.log(' ', d + ':', fs.readdirSync(dir).filter(f=>f.endsWith('.lua')).length, 'scripts');
});
